### ISSUE TITLE
medRQ - 52 instead of 53

### ISSUE THREAD

**Issue by onnokleen** [jonathancornelissen/highfrequency#10]
Nothing serious butI think there is a number wrong in your medRQ function. According to Andersen and Schaumburg (2012), the denominator should include a 52 instead of 53? See
[http://www.sciencedirect.com/science/article/pii/S0304407612000127](http://www.sciencedirect.com/science/article/pii/S0304407612000127)

Thank you very much for your awesome R package!

**Comment by kboudt** [comment]
Thanks! It has been corrected.

**Comment by payseur** [comment]
Closing.
