### ISSUE TITLE
Is ‘highfrequency’ available for R version 3.5.1?

### ISSUE THREAD

**Issue by chinghoo** [jonathancornelissen/highfrequency#14]
Hi there, 

I tried to install 'highfrequency' package but the warning shows the package is not available for R version 3.5.1. 

I would be grateful if anyone could let me know the way to install the package for my version.

Peace!
Bill Hoo
![default](https://user-images.githubusercontent.com/17788865/50221362-d220f680-03cf-11e9-80fa-85cca17f7eb5.PNG)

**Comment by payseur** [comment]
This works for me on R version 3.5.2 (2018-12-20) and all of the CRAN checks are working:

[https://cran.r-project.org/web/checks/check_results_highfrequency.html](https://cran.r-project.org/web/checks/check_results_highfrequency.html)
  
Maybe check your CRAN depository, or try to download it manually from CRAN and install the zip?
