### ISSUE TITLE
Issue with convert()

### ISSUE THREAD

**Issue by kristang** [jonathancornelissen/highfrequency#2]
When applying `convert()` to a .csv file from WRDS, I run into an issue where the convert function returns an error stating that the data destination folder does not exist. 
I thinks comes from a missing `dir.create()` command in the function.

There is code for the setting up the datadestination: 

```
    for (i in 1:length(dates)) {
      datasourcex = paste(datasource, "/", dates[i], sep = "")
      datadestinationx = paste(datadestination, "/", dates[i], 
        sep = "")
```

However, it is missing the `dir.create()` command, so the folders are never created, and the convert function returns an error stating that the folders cannot be found. 

Seems to work:

```
    for (i in 1:length(dates)) {
      datasourcex = paste(datasource, "/", dates[i], sep = "")
      datadestinationx = paste(datadestination, "/", dates[i], 
        sep = "")
     dir.create(datadestinationx)
```

**Comment by payseur** [comment]
Works for me, closing issue.  If issue occurs again please include more info on what WRDS data set works and what does not.
