### ISSUE TITLE
`convert` function creates folder structure, but no .RData file with TickData.com data

### ISSUE THREAD

**Issue by n-e-w** [jonathancornelissen/highfrequency#3]
I am new to using the package. The following issue is with TickData.com files.

I have setup the folders with a single day's worth of data for XYZ as per the documentation:

```
from = "2014-09-02"; 
to     = "2014-09-02"; 
datasource = "~/raw_data"; 
datadestination = "~/xts_data"
```

in `~/raw_data` I have placed the files:

```
XYZ_quotes.asc
XYZ_trades.asc
```

which are simply copied and renamed files from my original TickData folder. Note, I have **_not**_ extracted these using TickWrite7. These are just the raw .asc files from the download directory.

I then run the `convert` function as follows:

```
convert(from=from, to=to, datasource=datasource, datadestination=datadestination, trades = TRUE, quotes = TRUE, ticker="BHP", dir = TRUE, extension = "tickdatacom", header = FALSE, tradecolnames = NULL, quotecolnames = NULL, format = "%d/%m/%Y %H:%M:%OS")
```

(nb: i have tried this with header = TRUE and header = FALSE. The result is the same).

The function then proceeds to write the new directory and folder structure, but there are no .RData files once the folders are created. 

No errors were thrown when the function ran.

I've searched my machine to no avail.

I am using the latest github source for the package (v 0.3). Platform = R3.02. Win x86_64

Any advice much appreciated

**Comment by payseur** [comment]
Please include a link to the file so that we can reproduce.  Closing on 1-June-2017 as non-reproducible if not.

Thanks.

**Comment by payseur** [comment]
Closed from lack of reproducible information.
