### ISSUE TITLE
BNSjumptest error?

### ISSUE THREAD

**Issue by c00kiemonster** [jonathancornelissen/highfrequency#31]
I am getting an odd looking error when I run the example BNSjumptest function.

Is this a bug, or am I doing something wrong?

```
> library(highfrequency)
Loading required package: xts
Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

> data(sample_tdata)
> BNSjumptest(sample_tdata$PRICE, QVestimator= "RV", IVestimator= "minRV", IQestimator = "medRQ", type= "linear", makeReturns = TRUE)
Error in switch(IVestimator, RV = RV(rdata), BV = RBPVar(rdata), TV = rTPVar(rdata),  : 
  EXPR must be a length 1 vector
```

**Comment by kboudt** [comment]
Hi c00kiemonster, there is no argument QVestimator as it uses RV by default. 

BNSjumptest(sample_tdata$PRICE,  IVestimator= "minRV", 
            IQestimator = "medRQ", type= "linear", makeReturns = TRUE)

Do you have any paper in mind where they take another estimator than RV to estimate the total variation in the BNS jump test framework?

**Comment by c00kiemonster** [comment]
I must have copy pasted some legacy code, when I installed the `highfrequency` package from the github source I noticed the example code had changed. So now it's working ok. Sorry for the confusion!
