### ISSUE TITLE
The manual AJjumptest example gives an error

### ISSUE THREAD

**Issue by annoporci** [jonathancornelissen/highfrequency#4]
Example from page 11 of the Manual. Tested on 10 May 2015.

```
library("devtools")
install_github("highfrequency", "jonathancornelissen")
library("highfrequency")
data("sample_tdata")
ts <- sample_tdata$PRICE
AJjumptest(ts, p = 2, k = 3, 
    align.by = "seconds", 
    align.period = 5, 
    makeReturns = TRUE)
Error in seq.default(1, N, h) : invalid (to - from)/by in seq(.)
In addition: Warning message:
In FUN(x[(INDEX[y] + 1):INDEX[y + 1]], ...) : NAs introduced by coercion
```

**Comment by liangzhenghua** [comment]
Hi, I also have realized this problem, it seems that the bug has not been corrected, but I can run the example at https://rdrr.io/cran/highfrequency/man/BNSjumptest.html. It confused me that how can the wedsite can run the codes without this bug. If you have any solution, please just remind me, thank you!

**Comment by kboudt** [comment]
Hi the bug has been corrected. Wen running the above code I get  the following
$ztest
[1] 3.392276

$critical.value
[1] -1.959964  1.959964

$pvalue
[1] 0.0006931461

**Comment by payseur** [comment]
Corrected by Kris.
