### ISSUE TITLE
Tick data vendor

### ISSUE THREAD

**Issue by MislavSag** [jonathancornelissen/highfrequency#46]
I have just discovered your package. Where can we (small ,retail investors) get tick data in the first place?

I have found this site https://www.tickdata.com/, but the price is way to high.

Where did you get tick data from?

**Comment by stucash** [comment]
I'll just cut to the chase: `github` issues are created for raising (suspectedly) technical problems related to the package and nothing else. I'd suggest you google tick data and you should get enough information. Yes tick data is rarely free. FYI,  you can try dukascopy for tick data.
