### ISSUE TITLE
Request: Predict function for HAR / Heavy Model

### ISSUE THREAD

**Issue by JamesRTOK** [jonathancornelissen/highfrequency#5]
Hi,

Really useful package and well written.

It would be very useful if the predict method for the HAR / HEAVY models was implemented so
that out of sample predictions could be performed. As mentioned in the vignette, the linear regression coefficients can be extracted however, I think it would be less error prone to support 

```
predict(HarModel, new_log_return_data)
```

Rather than the user trying to calculate RV1, RV5, RV22, J1, J5 and J22.

Thank you

**Comment by vevilarinho** [comment]
Any developments in this direction?
