### ISSUE TITLE
cojump test

### ISSUE THREAD

**Issue by waynelapierre** [jonathancornelissen/highfrequency#50]
I couldn't find co-jump tests in the high-frequency r package. Do you have any plan of adding this test?

**Comment by kboudt** [comment]
Which cojump test do you want to see added?

**Comment by emilsjoerup** [comment]
I have added a test for cojumps.

It is the test in the paper Jumps in High-Frequency Data: Spurious Detections, Dynamics, and News by Pierre Bajgrowicz, Olivier Scaillet, and Adrien Treccani (2016)

You can find it here https://pubsonline.informs.org/doi/10.1287/mnsc.2015.2234 

You can get access to the code by installing the github version from this repository.

```
# install.packages("devtools")
library(devtools)
install_github("https://github.com/jonathancornelissen/highfrequency")
```

We will submit the code to CRAN soon.


Please also let us know if you want other cojump tests implemented :)

**Comment by waynelapierre** [comment]
That was quick! thanks so much for the hard work! 

By the way, I haven't used this highfrequency package. How is its performance?

**Comment by emilsjoerup** [comment]
I don't follow what you mean by

> By the way, I haven't used this highfrequency package. How is its performance?


Anyway,
Do you have any wishes for specific co-jump tests? We are actively working on the package and appreciate any requests.

**Comment by waynelapierre** [comment]
The cojump test you added solves my problem. I will try this package and let you know what I think. 

One thing I feel puzzled is that this package imports readr. My personal experience is all packages from the tidyverse are slow. Working with high-frequency data requires good performance, it is better to avoid tidyverse stuff.

**Comment by emilsjoerup** [comment]
> One thing I feel puzzled is that this package imports readr. My personal experience is all packages from the tidyverse are slow. Working with high-frequency data requires good performance, it is better to avoid tidyverse stuff.

This is no longer the case with the new version. For example we use data.table's fread instead :)

**Comment by waynelapierre** [comment]
This paper surveys the recent cojumps tests: 
 https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3225185
