### ISSUE TITLE
idiosyncratic jump

### ISSUE THREAD

**Issue by waynelapierre** [jonathancornelissen/highfrequency#52]
It would be great if the idiosyncratic jump is added to the highfrequency package. 

https://www.sciencedirect.com/science/article/pii/S0304405X18302393?casa_token=r7f-bOe7DwcAAAAA:mxKHStb87NGB2pj-K8ngfhliBZ_11TPTbPIWJ0U55au8paoIDmjwm2Qny2csWqEMbCh-VICn

**Comment by onnokleen** [comment]
We will look into it - btw., you are also very welcome to contribute code to this repostitory!

**Comment by onnokleen** [comment]
Why do you think it would be a good fit for the **highfrequency** package? The paper you cite is about daily data + option prices. Could you elaborate on the connection to intraday jump tests?

**Comment by waynelapierre** [comment]
I agree with you that it is not good to test jump stuff with daily data. 

Check this paper instead:

https://www.sciencedirect.com/science/article/abs/pii/S0304407620300129
