### ISSUE TITLE
Wrong scaling of 'TP' in BNSjumptest

### ISSUE THREAD

**Issue by avlanden** [jonathancornelissen/highfrequency#6]
The estimator of the tripower quarticity 'TP' is wrongly scaled in the BNSjumptest function of package highfrequency.

The function highfrequency:::rTPVar calculates the tripower quarticity as:

N/(N - 2) \* gamma(1/2)^2/(4 \* gamma(7/6)^2) \* sum(q^(4/3))

It should be, according to Huang and Tauchen (2005) among others:

(N^2)/(N - 2) \* 2^(2/3)_gamma(7/6)_gamma(1/2)^(-1) \* sum(q^(4/3))

such that both the 'N' scaling is wrong, and the 'gamma scaling' is wrong as well. Please look at page 461 of Huang and Tauchen (2005) for the 'n' scaling, and page 12 of the Andersen paper http://fic.wharton.upenn.edu/fic/papers/03/0333.pdf for the gamma scaling.

Best regards
Andreas Vig Logermann

References: 
title = {The Relative Contribution of Jumps to Total Price Variance},
author = {Huang, Xin and Tauchen, George},
year = {2005},
journal = {Journal of Financial Econometrics},

**Comment by kboudt** [comment]
Thx it will be corrected. I think that the mistake comes from a confusion between the tripower for iv and iq estimation. Giang wil correct it. Most recent code is on rforge where i am maintaining the package.

**Comment by avlanden** [comment]
Thank you, and thank you for providing such a nice package!

ons. 24. jun. 2015 kl. 19.32 skrev kboudt <notifications@github.com>:

**Comment by kristang** [comment]
Is there a reason for keeping development at rforge and not here :)?

**Comment by payseur** [comment]
R-Forge for highfrequency is deprecated.
