### ISSUE TITLE
24/7 trading period

### ISSUE THREAD

**Issue by waynelapierre** [jonathancornelissen/highfrequency#64]
For markets like FX, people trade 24/7. In such cases, how should marketOpen & marketClose be set?

**Comment by emilsjoerup** [comment]
Dear Wayne, can you be more specific? What is your problem? Which function(s) are you having trouble with, and what does your dataset look like? If you provide a little more information, we will have a much easier time helping you.

**Comment by waynelapierre** [comment]
My data contain tick-by-tick foreign exchange quotes. I am trying to use the aggregatePrice function. Since the foreign exchange market trade 24/7, is it OK to set the marketOpen to be "00:00:00" and marketClose to be "24:00:00"?

**Comment by emilsjoerup** [comment]
You can try it! Otherwise just set it to "23:59:59.99999", or something like that. This should give you your desired results and also show that your data still belongs to that day ("00:00:00" would be next day). I am actually not sure if the "24:00:00" input is valid.

**Comment by waynelapierre** [comment]
OK. I will try "00:00:00.001" and "23:59:59.999". Thanks for the suggestion.
