### ISSUE TITLE
missing convert function

### ISSUE THREAD

**Issue by patricklucescu** [jonathancornelissen/highfrequency#70]
Hi everyone. I have just installed this library and I was trying to convert some tick TAQ data from csv to xts using the **convert** function. However, it seems that the function is not included in the library anymore. Has it been deprecated? If yes, how would you recommend to load a huge csv file?

Thanks!

**Comment by emilsjoerup** [comment]
Dear Patrick,

I don't know of this `convert` function you mention, which leads me to think it's been deprecated and removed for two or more years.

If you are looking to load a big csv file we recommend the `fread` function in the `data.table` package - it is an excellent function and gives you a `data.table` which we use internally.

Unfortunately, if you want an `xts` object you will have to create it yourself.

Best,
Emil

**Comment by patricklucescu** [comment]
Dear Emil,

Thanks a lot! There seem to be a lot of documentation/blog posts covering this function (see [link](https://www.rdocumentation.org/packages/highfrequency/versions/0.5.3/topics/convert)), including on your official website I belive ([link](http://highfrequency.herokuapp.com/authors.html)). 

Many thanks for the recommended `fread`. It seems to be exactly what I was looking for:)

Best,
Patrick
