### ISSUE TITLE
Missing noZeroPrices function

### ISSUE THREAD

**Issue by Tigrosso** [jonathancornelissen/highfrequency#82]
Hi, I'm missing the noZeroPrices function in the latest version of the Highfrequency package
<img width="1468" alt="Screenshot 2022-01-12 at 14 21 28" src="https://user-images.githubusercontent.com/97607774/149148266-75addd61-35a2-4abe-96b8-a75a85a229ed.png">

**Comment by onnokleen** [comment]
Dear Tigrosse, I am looking into it but it looks like the export flag is missing for that function in the newest version. I'll let you know asap.

**Comment by onnokleen** [comment]
You can install an updated version with the correct export via the devtools package from my personal fork

`devtools::install_github("onnokleen/highfrequency")`

until the fixed version is on cran.

**Comment by Tigrosso** [comment]
Hi Onno, 

Thanks for your response, could you please give some more information on how I can install the package? I tried to install your version, but I keep getting errors.
<img width="1236" alt="Screenshot 2022-01-13 at 10 44 38" src="https://user-images.githubusercontent.com/97607774/149306065-ccb19e7c-b2d7-4ccc-a616-9012fc0d2b50.png">

**Comment by onnokleen** [comment]
Hi Tigrosso,

It seems that you don't have the right toolchain installed on your computer, see the error about gfortran missing. We already submitted the updated version to CRAN. Hence, it might be easiest to just wait until CRAN releases it.

**Comment by Tigrosso** [comment]
Hi Onne,

I will, thanks again for all the help:)
