### ISSUE TITLE
How to choose a suitable realized volatility estimator

### ISSUE THREAD

**Issue by fecet** [jonathancornelissen/highfrequency#85]
Sorry, this can be a silly question. As there are so many realized measures in `highfrequency`, how to know which one is better and should be used in practice? Is there a function to tell us the "predicted accuracy" or something else?

Any help I would appreciate, thank you for your great work.

**Comment by onnokleen** [comment]
Hi fecet, unfortunately there is no good way of giving general advice. There are different estimators for different needs that may also perform differently on different data sets :) 
@kboudt I think this issue can also be closed?
