### ISSUE TITLE
Is the parzen kernel implemented correctly

### ISSUE THREAD

**Issue by travis-leith** [jonathancornelissen/highfrequency#91]
I am reading through "Analyzing intraday financial data in R: The highfrequency package". There are many new concepts and in the interests of time, I am limiting myself to go 1 reference deep. 

I see the definition of the parzen kernel according to Barndorff-Nielsen et al (2008) is 
![image](https://user-images.githubusercontent.com/29927084/170489552-10c53375-3575-46f8-92cd-6adf17ee24e0.png)
and according to 
Barndorff-Nielsen et al (2009)
![image](https://user-images.githubusercontent.com/29927084/170489605-969c9a29-3e53-4b52-b9d0-23ff5018336d.png)
Note that the function is $0$ for $x>1$.

Your implementation is not consistent with this

```
case 9: //Parzen
    if (thex > .5) {
      return( 2*(1-thex)*(1-thex)*(1-thex));
    }  else {
      return(1- 6 * pow(thex, 2.0) +6 * pow(thex, 3.0));
    }
    break;
```

but I don't know if the domain of this function is restricted in some other part of the code, such that this is not a problem.

**Comment by onnokleen** [comment]
Hi travis-leith, thanks a lot for your feedback. I will look into it but June is really busy so it might take a while for my final response. Best, Onno

**Comment by onnokleen** [comment]
Hi travis-leith, sorry for the late reply: The implementation is fine as is in my opinion. as we are not submitting any number larger than one as you can see in line 98 of realizedMeasures.cpp. @kboudt Can you close this issue?
